[tls.options]
  [tls.options.secure]
    minVersion = "VersionTLS12"
    sniStrict = true
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    ]

[http.middlewares]
  [http.middlewares.secure.headers]
    stsSeconds = 31536000
    stsIncludeSubdomains = true
    forceStsHeader = true
    sslRedirect = true
    sslForceHost = true